# EDA Aves en Peligro de extinción

Análisis de datos sobre aves en peligro de extinción en España, así como exploración de datos sobre planes de protección y acción de cada CCAA. Se buscaran patrones y visualizaciones de estos datos con el fin de crear un mapa visual e interactivo de fácil acceso para visualizar la situación de las aves y sus planes en España.

In [1]:
#IMportamos librerias
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt

In [2]:
pd.set_option("display.max_rows", 20)

## Exploración básica del dataset --> Pagina Catalogos

Estas son las variables por entrada que contiene este dataset:

- **FAMILIA:**  Unidad sistematica y categorica taxonomica de las aves.
- **Especie_Nombre_científico:**    Nombre cientifico de la especie a la que se pertenece.
- **Subespecie:**   Grupo en el que se dividen las especies
- **Espacie_Castellano:**   Nombre en castellano de la especie a la que se pertenece.
- **Ordenación_taxonomica:**    Cada grupo en el que se dividen los organismos emparentados. 
- **NOMBRE COMUN:**  Nombre del ave
- **NOMBRE CIENTIFICO:**    Nombre cientifico de las ave
- **LR2004 (*Canarias):**   Libro Rojo de las Aves de España en el año 2004 de Canarias
- **LISTA ROJA 2021 Invern./Migrat.:**  Amenazas a las aves migratorias en el año 2021
- **LISTA ROJA 2021 Reproductoras (*Canarias):** Amenazas a las aves reproductoras en el año 2021 en Canarias
- **CEEA y LESRPE:**    Amenazas a nivel nacional
- **D. Aves:**   Documento para la conservación de Aves de la Union Europea.
- **EUROPEAN IUCN RED LIST BIRDS (2015):** Lista roja europea de la International Union for the Conservation of Nature (IUCN) del año 2015
- **EUROPEAN IUCN RED LIST BIRDS (2021):** Lista roja europea de la International Union for the Conservation of Nature (IUCN) del año 2021
- **GLOBAL UICN RED LIST (consulta 2022):** Lista roja global del International Union for the Conservation of Nature (IUCN) del año 2022
- **GLOBAL UICN RED LIST (LAST ASSESSED):** ULtima revision de la lista roja global por la International Union for the Conservation of Nature (IUCN) 
- **CON_BERN:** Bern Convention
- **CON_BONN:** Convencion en la conservacion de especies migratorias de especies salvajes. Es un tratado global de las Naciones Unidas.
- **CON_CITES:** Convención sobre el Comercio Internacional de Especies Amenazadas de Fauna y Flora Silvestres

## Exploración básica del dataset --> Pagina SPS-Planes

Estas son las variables por entrada que contiene este dataset:

- **NOMBRE COMUN:**  Nombre del ave
- **NOMBRE CIENTIFICO:**    Nombre cientifico de las ave
- **ESTRATEGIA ESTATAL:** Plan de accion nacional
- **Planes Acción Comisión Europea:** Planes a nivel europeo
- **Planes Acción AEWA:** Acuerdo de conservacion de las aves acuaticas migratorias afroeurasiaticas 
- **Planes Manejo Especies Cinegéticas Comisión Europea:** Plan europeo para la proteccion de animales que pueden ser objeto de caza.

| CCAA                | Nombre Completo                                                                                   | 
|---------------------|---------------------------------------------------------------------------------------------------|
| `AND`               | Catálogo Andaluz de Especies Amenazadas                                                           | 
| `ARA`               | Catálogo de Especies Amenazadas de Aragón                                                         | 
| `AST`               | Catálogo Regional de especies amenazadas de fauna vertebrada del Pincipado de Asturias            | 
| `BAL`               | Catálogo Balear de Especies Amenazadas y de Especial Protección                                   | 
| `CANA`              | Catálogo Canario de Especies Protegidas                                                           |     
| `CANT`              | Catálogo Regional de Especies Amenazadas de Cantabria                                             | 
| `CAT`               | Catálogo de la Fauna Amenazada de Cataluña                                                        | 
| `CLM`               | Catálogo Regional de Especies Amenazadas de Castilla-La Mancha                                    | 
| `CYL`               | Catálogo Especies Amenazadas de Castilla y León                                                   | 
| `EUSK`              | Catálogo Vasco de Especies Amenazadas la la Fauna y Flora Silvestre y Marina                      | 
| `EXT`               | Catálogo Regional de Especies Amenazadas de Extremadura                                           | 
| `GAL`               | Catálogo galego de especies amenazadas                                                            | 
| `MAD`               | Catálogo Regional de especies amenazadas de fauna y flora silvestres                              | 
| `MUR`               | Catálogo de especies amenazadas de fauna silvestre de la Región de Murcia                         | 
| `NAV`               | Catálogo de Especies Amenazadas de Navarra                                                        | 
| `RIO`               | Catálogo de La Rioja de Especies de Fauna                                                         | 
| `VAL`               | Catálogo Valenciano de Especies de Fauna Amenazada                                                |

In [3]:
#Se lee pagina del catalogo de aves
aves = pd.read_excel('./data_raw/Catalogacion_Especies_Aves_y_Planes_accion_12-2022.xlsx', sheet_name = 'Catálogos' )
aves

,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
0,MEROPIDAE,Merops apiaster,NaN,Abejaruco europeo,490.0,Abejaruco europeo,Merops apiaster,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2016.0,II,II,NaN
1,ACCIPITRIDAE,Pernis apivorus,NaN,Abejero europeo,174.0,Abejero europeo,Pernis apivorus,LC,NaN,NT,...,DIE,NaN,NaN,LC,LC,LC,2021.0,II,II,C1
2,UPUPIDAE,Upupa epops,epops,Abubilla común,491.0,Abubilla común,Upupa epops,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2020.0,II,NaN,NaN
3,PRUNELLIDAE,Prunella collaris,collaris,Acentor alpino,784.0,Acentor alpino,Prunella collaris,NE,NaN,NT,...,DIE,NaN,NaN,LC,LC,LC,2016.0,II,NaN,NaN
4,PRUNELLIDAE,Prunella modularis,"modularis, mabbotti",Acentor común,785.0,Acentor común,Prunella modularis,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2018.0,II,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Zorzal alirrojo,Turdus iliacus,NE,DD,NaN,...,NaN,NaN,NaN,NT,LC,NT,2016.0,III,NaN,NaN
380,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Zorzal charlo,Turdus viscivorus,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN
381,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Zorzal común,Turdus philomelos,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2018.0,III,NaN,NaN
382,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Zorzal real,Turdus pilaris,NE,DD,NaN,...,NaN,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN
383,PHYLLOSCOPIDAE,NaN,NaN,NaN,642.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#Informacion de la pagina en el dataset
aves.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384 entries, 0 to 383
Data columns (total 36 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   FAMILIA                                    370 non-null    object
 1   Especie_Nombre_científico                  357 non-null    object
 2   subespecie                                 221 non-null    object
 3   Especie_Castellano                         357 non-null    object
 4   Ordenación_taxonómica                      371 non-null    float64
 5   NOMBRE COMÚN                               383 non-null    object
 6   NOMBRE CIENTÍFICO                          383 non-null    object
 7   LR2004 (*Canarias)                         381 non-null    object
 8   LISTA ROJA 2021 Invern./Migrat.            128 non-null    object
 9   LISTA ROJA 2021 Reproductoras (*Canarias)  299 non-null    object
 10  CEEA y LESRPE                              289 non-null    object
 11  D. Aves                                    200 non-null    object
 12  AND                                        272 non-null    object
 13  ARA                                        37 non-null     object
 14  AST                                        11 non-null     object
 15  BAL                                        198 non-null    object
 16  CANA                                       61 non-null     object
 17  CANT                                       11 non-null     object
 18  CAT                                        272 non-null    object
 19  CLM                                        211 non-null    object
 20  CYL                                        0 non-null      float64
 21  EUSK                                       94 non-null     object
 22  EXT                                        217 non-null    object
 23  GAL                                        30 non-null     object
 24  MAD                                        61 non-null     object
 25  MUR                                        42 non-null     object
 26  NAV                                        87 non-null     object
 27  RIO                                        3 non-null      object
 28  VAL                                        42 non-null     object
 29  EUROPEAN IUCN RED LIST BIRDS (2015)        360 non-null    object
 30  EUROPEAN IUCN RED LIST BIRDS (2021)        372 non-null    object
 31  GLOBAL UICN RED LIST (consulta 2022)       372 non-null    object
 32  GLOBAL UICN RED LIST (LAST ASSESSED)       372 non-null    float64
 33  CON_BERN                                   350 non-null    object
 34  CON_BONN                                   157 non-null    object
 35  CON_CITES                                  42 non-null     object
dtypes: float64(3), object(33)
memory usage: 108.1+ KB

In [5]:
#Eliminamos ultimo registro que no contiene informacion
aves.drop(axis=0, index=383, inplace=True)
aves.tail()

,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
378,ACROCEPHALIDAE,Hippolais polyglotta,NaN,Zarcero políglota,661.0,Zarcero políglota,Hippolais polyglotta,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2016.0,II,II,NaN
379,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Zorzal alirrojo,Turdus iliacus,NE,DD,NaN,...,NaN,NaN,NaN,NT,LC,NT,2016.0,III,NaN,NaN
380,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Zorzal charlo,Turdus viscivorus,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN
381,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Zorzal común,Turdus philomelos,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2018.0,III,NaN,NaN
382,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Zorzal real,Turdus pilaris,NE,DD,NaN,...,NaN,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN

In [6]:
aves['LR2004 (*Canarias)'].value_counts()

NE          241
VU           40
NT           24
EN           21
DD           12
           ...
EN/NT*        1
NE/NT*        1
EN/CR*        1
NT/DD*        1
NT-EN/CR      1
Name: LR2004 (*Canarias), Length: 21, dtype: int64

- Hay mayoría de aves en peligro de extinción, la segunda categoría mayoritaria es Vulnerables. En Canarias(2004)

In [7]:
#planes = pd.read_excel('Catalogacion_Especies_Aves_y_Planes_accion_12-2022.xlsx', sheet_name = 'SPS-Planes' )
#planes

#### Vamos a unir un dataset de aves de La Rioja que teníamos en un pdf a parte. Esto lo hacemos porque en el dataset original de aves no teníamos datos sobre las aves de la rioja

In [8]:
# Cargamos el dataset de la Riejo, como vemos habrá que hacer unos arreglos
rioja = pd.read_excel('./data_raw/aves_rioja_actual.xlsx')
rioja

,Núm. 42 Sábado 18 de febrero de 2023 Sec. I. Pág. 24926,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN
1,NaN,NaN,NaN
2,Nombre científico,Nombre común,Categoría del catálogo
3,Accipiter gentilis.,Azor común.,NaN
4,Accipiter nisus.,Gavilán.,NaN
...,...,...,...
207,Tringa totanus.,Archibebe común.,NaN
208,Troglodytes troglodytes.,Chochín común.,NaN
209,Turdus torquatus.,Mirlo capiblanco.,NaN
210,Tyto alba.,Lechuza común.,NaN
211,Upupa epops.,Abubilla.,NaN

In [9]:
# Eliminamos las dos primeras filas que no aportan información
rioja = rioja.drop([0, 1], axis=0)
rioja

,Núm. 42 Sábado 18 de febrero de 2023 Sec. I. Pág. 24926,Unnamed: 1,Unnamed: 2
2,Nombre científico,Nombre común,Categoría del catálogo
3,Accipiter gentilis.,Azor común.,NaN
4,Accipiter nisus.,Gavilán.,NaN
5,Acrocephalus arundinaceus.,Carricero tordal.,NaN
6,Acrocephalus paludicola.,Carricerín cejudo.,NaN
...,...,...,...
207,Tringa totanus.,Archibebe común.,NaN
208,Troglodytes troglodytes.,Chochín común.,NaN
209,Turdus torquatus.,Mirlo capiblanco.,NaN
210,Tyto alba.,Lechuza común.,NaN
211,Upupa epops.,Abubilla.,NaN

In [10]:
# REnombramos las columnas
riojaa = rioja.rename({'Núm.42 Sábado 18 de febrero de 2023 Sec. I. Pág. 24926': 'Nombre científico', 'Unnamed: 1': 'NOMBRE COMÚN', 'Unnamed: 2': 'RIO2'}, axis=1)
riojaa

,Núm. 42 Sábado 18 de febrero de 2023 Sec. I. Pág. 24926,NOMBRE COMÚN,RIO2
2,Nombre científico,Nombre común,Categoría del catálogo
3,Accipiter gentilis.,Azor común.,NaN
4,Accipiter nisus.,Gavilán.,NaN
5,Acrocephalus arundinaceus.,Carricero tordal.,NaN
6,Acrocephalus paludicola.,Carricerín cejudo.,NaN
...,...,...,...
207,Tringa totanus.,Archibebe común.,NaN
208,Troglodytes troglodytes.,Chochín común.,NaN
209,Turdus torquatus.,Mirlo capiblanco.,NaN
210,Tyto alba.,Lechuza común.,NaN
211,Upupa epops.,Abubilla.,NaN

In [11]:
rioja = riojaa.drop([2], axis=0)
rioja

,Núm. 42 Sábado 18 de febrero de 2023 Sec. I. Pág. 24926,NOMBRE COMÚN,RIO2
3,Accipiter gentilis.,Azor común.,NaN
4,Accipiter nisus.,Gavilán.,NaN
5,Acrocephalus arundinaceus.,Carricero tordal.,NaN
6,Acrocephalus paludicola.,Carricerín cejudo.,NaN
7,Acrocephalus schoenobaenus.,Carricerín común.,NaN
...,...,...,...
207,Tringa totanus.,Archibebe común.,NaN
208,Troglodytes troglodytes.,Chochín común.,NaN
209,Turdus torquatus.,Mirlo capiblanco.,NaN
210,Tyto alba.,Lechuza común.,NaN
211,Upupa epops.,Abubilla.,NaN

#### Se elimino la fila número 2

In [12]:
# Eliminamos el punto al final del nombre común, que luego podría dar conflicto al unirlo al dataset original.
rioja["NOMBRE COMÚN"].replace({'\.':''}, regex=True, inplace=True)
rioja

,Núm. 42 Sábado 18 de febrero de 2023 Sec. I. Pág. 24926,NOMBRE COMÚN,RIO2
3,Accipiter gentilis.,Azor común,NaN
4,Accipiter nisus.,Gavilán,NaN
5,Acrocephalus arundinaceus.,Carricero tordal,NaN
6,Acrocephalus paludicola.,Carricerín cejudo,NaN
7,Acrocephalus schoenobaenus.,Carricerín común,NaN
...,...,...,...
207,Tringa totanus.,Archibebe común,NaN
208,Troglodytes troglodytes.,Chochín común,NaN
209,Turdus torquatus.,Mirlo capiblanco,NaN
210,Tyto alba.,Lechuza común,NaN
211,Upupa epops.,Abubilla,NaN

In [13]:
# La columna de nombre científico no la necesitamos, la eliminamos.
rioja = rioja.drop(['Núm. 42                                                          Sábado 18 de febrero de 2023                                        Sec. I.   Pág. 24926'], axis=1)
rioja

          NOMBRE COMÚN RIO2
3           Azor común  NaN
4              Gavilán  NaN
5     Carricero tordal  NaN
6    Carricerín cejudo  NaN
7     Carricerín común  NaN
..                 ...  ...
207    Archibebe común  NaN
208      Chochín común  NaN
209   Mirlo capiblanco  NaN
210      Lechuza común  NaN
211           Abubilla  NaN

[209 rows x 2 columns]

### Se elimina la columna 1er

In [14]:
print(rioja.columns.values)

['NOMBRE COMÚN' 'RIO2']

In [15]:
rioja.set_index('NOMBRE COMÚN',inplace=True)
rioja

                  RIO2
NOMBRE COMÚN
Azor común         NaN
Gavilán            NaN
Carricero tordal   NaN
Carricerín cejudo  NaN
Carricerín común   NaN
...                ...
Archibebe común    NaN
Chochín común      NaN
Mirlo capiblanco   NaN
Lechuza común      NaN
Abubilla           NaN

[209 rows x 1 columns]

### Cambiamos los  indices a nombre común

In [16]:
rioja.dropna(inplace=True)
rioja

                                           RIO2
NOMBRE COMÚN
Buitre negro                        Vulnerable.
Águila-azor perdicera  En peligro de extinción.
Porrón pardo           En peligro de extinción.
Avetoro común          En peligro de extinción.
Chorlito carambolo                  Vulnerable.
Fumarel común          En peligro de extinción.
Cigüeña negra                       Vulnerable.
Aguilucho cenizo                    Vulnerable.
Escribano palustre     En peligro de extinción.
Cernícalo primilla                  Vulnerable.
Quebrantahuesos        En peligro de extinción.
Milano real            En peligro de extinción.
Alimoche común                      Vulnerable.
Águila pescadora                    Vulnerable.
Perdiz pardilla        En peligro de extinción.
Colirrojo real                      Vulnerable.
Ganga ibérica          En peligro de extinción.
Ganga ortega           En peligro de extinción.
Sisón común            En peligro de extinción.

### Se borran los NaN y solo se quedan los que tienen amenazas

In [17]:
rioja.replace({"Vulnerable.": 'VU', "En peligro de extinción.": 'EN'}, inplace=True)
rioja

                      RIO2
NOMBRE COMÚN
Buitre negro            VU
Águila-azor perdicera   EN
Porrón pardo            EN
Avetoro común           EN
Chorlito carambolo      VU
Fumarel común           EN
Cigüeña negra           VU
Aguilucho cenizo        VU
Escribano palustre      EN
Cernícalo primilla      VU
Quebrantahuesos         EN
Milano real             EN
Alimoche común          VU
Águila pescadora        VU
Perdiz pardilla         EN
Colirrojo real          VU
Ganga ibérica           EN
Ganga ortega            EN
Sisón común             EN

#### Se cambian las nomenclaturas de la tabla de catalogación

In [18]:
#rioja.drop('Nombre común', axis=0, inplace=True)
#rioja

In [19]:
rioja.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, Buitre negro to Sisón común
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RIO2    19 non-null     object
dtypes: object(1)
memory usage: 304.0+ bytes

In [20]:
aves.set_index('NOMBRE COMÚN',inplace=True)

### Cambiamos el indice de la tabla de Catalogación  a "NOMBRE COMÚN"

In [21]:
df_final = pd.concat([aves,rioja],axis=1,sort=False).reset_index()
df_final

,NOMBRE COMÚN,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,RIO2
0,Abejaruco europeo,MEROPIDAE,Merops apiaster,NaN,Abejaruco europeo,490.0,Merops apiaster,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2016.0,II,II,NaN,NaN
1,Abejero europeo,ACCIPITRIDAE,Pernis apivorus,NaN,Abejero europeo,174.0,Pernis apivorus,LC,NaN,NT,...,NaN,NaN,LC,LC,LC,2021.0,II,II,C1,NaN
2,Abubilla común,UPUPIDAE,Upupa epops,epops,Abubilla común,491.0,Upupa epops,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2020.0,II,NaN,NaN,NaN
3,Acentor alpino,PRUNELLIDAE,Prunella collaris,collaris,Acentor alpino,784.0,Prunella collaris,NE,NaN,NT,...,NaN,NaN,LC,LC,LC,2016.0,II,NaN,NaN,NaN
4,Acentor común,PRUNELLIDAE,Prunella modularis,"modularis, mabbotti",Acentor común,785.0,Prunella modularis,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2018.0,II,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,Zorzal alirrojo,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Turdus iliacus,NE,DD,NaN,...,NaN,NaN,NT,LC,NT,2016.0,III,NaN,NaN,NaN
380,Zorzal charlo,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Turdus viscivorus,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN,NaN
381,Zorzal común,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Turdus philomelos,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2018.0,III,NaN,NaN,NaN
382,Zorzal real,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Turdus pilaris,NE,DD,NaN,...,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN,NaN
383,Águila-azor perdicera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EN

### Unimos la tabla Catalogación y Aves Rioja

In [22]:
df_final.drop(['RIO'], axis=1, inplace=True)
df_final

,NOMBRE COMÚN,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,NAV,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,RIO2
0,Abejaruco europeo,MEROPIDAE,Merops apiaster,NaN,Abejaruco europeo,490.0,Merops apiaster,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2016.0,II,II,NaN,NaN
1,Abejero europeo,ACCIPITRIDAE,Pernis apivorus,NaN,Abejero europeo,174.0,Pernis apivorus,LC,NaN,NT,...,DIE,NaN,LC,LC,LC,2021.0,II,II,C1,NaN
2,Abubilla común,UPUPIDAE,Upupa epops,epops,Abubilla común,491.0,Upupa epops,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2020.0,II,NaN,NaN,NaN
3,Acentor alpino,PRUNELLIDAE,Prunella collaris,collaris,Acentor alpino,784.0,Prunella collaris,NE,NaN,NT,...,DIE,NaN,LC,LC,LC,2016.0,II,NaN,NaN,NaN
4,Acentor común,PRUNELLIDAE,Prunella modularis,"modularis, mabbotti",Acentor común,785.0,Prunella modularis,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2018.0,II,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,Zorzal alirrojo,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Turdus iliacus,NE,DD,NaN,...,NaN,NaN,NT,LC,NT,2016.0,III,NaN,NaN,NaN
380,Zorzal charlo,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Turdus viscivorus,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN,NaN
381,Zorzal común,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Turdus philomelos,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2018.0,III,NaN,NaN,NaN
382,Zorzal real,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Turdus pilaris,NE,DD,NaN,...,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN,NaN
383,Águila-azor perdicera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EN

### Se procede a borrar la columna Rio de catalogación (vacio) y nos quedamos con la de Aves Rioja

In [23]:
df_final.rename({"RIO2": 'RIO'}, axis=1, inplace=True)
df_final

,NOMBRE COMÚN,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,NAV,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,RIO
0,Abejaruco europeo,MEROPIDAE,Merops apiaster,NaN,Abejaruco europeo,490.0,Merops apiaster,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2016.0,II,II,NaN,NaN
1,Abejero europeo,ACCIPITRIDAE,Pernis apivorus,NaN,Abejero europeo,174.0,Pernis apivorus,LC,NaN,NT,...,DIE,NaN,LC,LC,LC,2021.0,II,II,C1,NaN
2,Abubilla común,UPUPIDAE,Upupa epops,epops,Abubilla común,491.0,Upupa epops,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2020.0,II,NaN,NaN,NaN
3,Acentor alpino,PRUNELLIDAE,Prunella collaris,collaris,Acentor alpino,784.0,Prunella collaris,NE,NaN,NT,...,DIE,NaN,LC,LC,LC,2016.0,II,NaN,NaN,NaN
4,Acentor común,PRUNELLIDAE,Prunella modularis,"modularis, mabbotti",Acentor común,785.0,Prunella modularis,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2018.0,II,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,Zorzal alirrojo,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Turdus iliacus,NE,DD,NaN,...,NaN,NaN,NT,LC,NT,2016.0,III,NaN,NaN,NaN
380,Zorzal charlo,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Turdus viscivorus,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN,NaN
381,Zorzal común,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Turdus philomelos,NE,NaN,LC,...,NaN,NaN,LC,LC,LC,2018.0,III,NaN,NaN,NaN
382,Zorzal real,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Turdus pilaris,NE,DD,NaN,...,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN,NaN
383,Águila-azor perdicera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EN

### Cambiamos el nombre de RIO2 a RIO

In [24]:
df_final = df_final.reindex(columns=['FAMILIA','Especie_Nombre_científico','subespecie','Especie_Castellano',
 'Ordenación_taxonómica', 'NOMBRE COMÚN', 'NOMBRE CIENTÍFICO',
 'LR2004 (*Canarias)', 'LISTA ROJA 2021 Invern./Migrat.',
 'LISTA ROJA 2021 Reproductoras (*Canarias)', 'CEEA y LESRPE', 'D. Aves',
 'AND', 'ARA', 'AST', 'BAL', 'CANA', 'CANT', 'CAT', 'CLM', 'CYL', 'EUSK', 'EXT',
 'GAL', 'MAD', 'MUR', 'NAV', 'RIO', 'VAL', 'EUROPEAN IUCN RED LIST BIRDS (2015)',
 'EUROPEAN IUCN RED LIST BIRDS (2021)',
 'GLOBAL UICN RED LIST (consulta 2022)',
 'GLOBAL UICN RED LIST (LAST ASSESSED)', 'CON_BERN', 'CON_BONN', 'CON_CITES'])
df_final

,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
0,MEROPIDAE,Merops apiaster,NaN,Abejaruco europeo,490.0,Abejaruco europeo,Merops apiaster,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2016.0,II,II,NaN
1,ACCIPITRIDAE,Pernis apivorus,NaN,Abejero europeo,174.0,Abejero europeo,Pernis apivorus,LC,NaN,NT,...,DIE,NaN,NaN,LC,LC,LC,2021.0,II,II,C1
2,UPUPIDAE,Upupa epops,epops,Abubilla común,491.0,Abubilla común,Upupa epops,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2020.0,II,NaN,NaN
3,PRUNELLIDAE,Prunella collaris,collaris,Acentor alpino,784.0,Acentor alpino,Prunella collaris,NE,NaN,NT,...,DIE,NaN,NaN,LC,LC,LC,2016.0,II,NaN,NaN
4,PRUNELLIDAE,Prunella modularis,"modularis, mabbotti",Acentor común,785.0,Acentor común,Prunella modularis,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2018.0,II,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Zorzal alirrojo,Turdus iliacus,NE,DD,NaN,...,NaN,NaN,NaN,NT,LC,NT,2016.0,III,NaN,NaN
380,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Zorzal charlo,Turdus viscivorus,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN
381,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Zorzal común,Turdus philomelos,NE,NaN,LC,...,NaN,NaN,NaN,LC,LC,LC,2018.0,III,NaN,NaN
382,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Zorzal real,Turdus pilaris,NE,DD,NaN,...,NaN,NaN,NaN,LC,LC,LC,2016.0,III,NaN,NaN
383,NaN,NaN,NaN,NaN,NaN,Águila-azor perdicera,NaN,NaN,NaN,NaN,...,NaN,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Ubicamos la columna RIO en su lugar original

In [25]:
df_final.RIO =df_final.RIO.fillna(value='No Presente')
df_final

,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
0,MEROPIDAE,Merops apiaster,NaN,Abejaruco europeo,490.0,Abejaruco europeo,Merops apiaster,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2016.0,II,II,NaN
1,ACCIPITRIDAE,Pernis apivorus,NaN,Abejero europeo,174.0,Abejero europeo,Pernis apivorus,LC,NaN,NT,...,DIE,No Presente,NaN,LC,LC,LC,2021.0,II,II,C1
2,UPUPIDAE,Upupa epops,epops,Abubilla común,491.0,Abubilla común,Upupa epops,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2020.0,II,NaN,NaN
3,PRUNELLIDAE,Prunella collaris,collaris,Acentor alpino,784.0,Acentor alpino,Prunella collaris,NE,NaN,NT,...,DIE,No Presente,NaN,LC,LC,LC,2016.0,II,NaN,NaN
4,PRUNELLIDAE,Prunella modularis,"modularis, mabbotti",Acentor común,785.0,Acentor común,Prunella modularis,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2018.0,II,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Zorzal alirrojo,Turdus iliacus,NE,DD,NaN,...,NaN,No Presente,NaN,NT,LC,NT,2016.0,III,NaN,NaN
380,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Zorzal charlo,Turdus viscivorus,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2016.0,III,NaN,NaN
381,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Zorzal común,Turdus philomelos,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2018.0,III,NaN,NaN
382,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Zorzal real,Turdus pilaris,NE,DD,NaN,...,NaN,No Presente,NaN,LC,LC,LC,2016.0,III,NaN,NaN
383,NaN,NaN,NaN,NaN,NaN,Águila-azor perdicera,NaN,NaN,NaN,NaN,...,NaN,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Nombramos los datos vacios en RIO por NO PRESENTE

In [26]:
display(df_final)

,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
0,MEROPIDAE,Merops apiaster,NaN,Abejaruco europeo,490.0,Abejaruco europeo,Merops apiaster,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2016.0,II,II,NaN
1,ACCIPITRIDAE,Pernis apivorus,NaN,Abejero europeo,174.0,Abejero europeo,Pernis apivorus,LC,NaN,NT,...,DIE,No Presente,NaN,LC,LC,LC,2021.0,II,II,C1
2,UPUPIDAE,Upupa epops,epops,Abubilla común,491.0,Abubilla común,Upupa epops,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2020.0,II,NaN,NaN
3,PRUNELLIDAE,Prunella collaris,collaris,Acentor alpino,784.0,Acentor alpino,Prunella collaris,NE,NaN,NT,...,DIE,No Presente,NaN,LC,LC,LC,2016.0,II,NaN,NaN
4,PRUNELLIDAE,Prunella modularis,"modularis, mabbotti",Acentor común,785.0,Acentor común,Prunella modularis,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2018.0,II,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Zorzal alirrojo,Turdus iliacus,NE,DD,NaN,...,NaN,No Presente,NaN,NT,LC,NT,2016.0,III,NaN,NaN
380,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Zorzal charlo,Turdus viscivorus,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2016.0,III,NaN,NaN
381,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Zorzal común,Turdus philomelos,NE,NaN,LC,...,NaN,No Presente,NaN,LC,LC,LC,2018.0,III,NaN,NaN
382,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Zorzal real,Turdus pilaris,NE,DD,NaN,...,NaN,No Presente,NaN,LC,LC,LC,2016.0,III,NaN,NaN
383,NaN,NaN,NaN,NaN,NaN,Águila-azor perdicera,NaN,NaN,NaN,NaN,...,NaN,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df_final.iloc[230]

FAMILIA                                 PARIDAE
Especie_Nombre_científico                   NaN
subespecie                                  NaN
Especie_Castellano                          NaN
Ordenación_taxonómica                     580.0
                                         ...
GLOBAL UICN RED LIST (consulta 2022)         LC
GLOBAL UICN RED LIST (LAST ASSESSED)     2016.0
CON_BERN                                     II
CON_BONN                                    NaN
CON_CITES                                   NaN
Name: 230, Length: 36, dtype: object

#### Este es el único dato cuya amenaza es nombrada mal, pues usa una ',' en vez de un '/' para indicar el tipo de amenaza. Esto nos dará problemas en un futuro así que lo cambiaremos. Pasaremos de 'DIE, VU' a 'DIE/VU'

In [28]:
df_final['CANA'][230]='DIE/VU'

/tmp/ipykernel_4284/2124447151.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['CANA'][230]='DIE/VU'

In [29]:
df_final.iloc[230]

FAMILIA                                 PARIDAE
Especie_Nombre_científico                   NaN
subespecie                                  NaN
Especie_Castellano                          NaN
Ordenación_taxonómica                     580.0
                                         ...
GLOBAL UICN RED LIST (consulta 2022)         LC
GLOBAL UICN RED LIST (LAST ASSESSED)     2016.0
CON_BERN                                     II
CON_BONN                                    NaN
CON_CITES                                   NaN
Name: 230, Length: 36, dtype: object

In [30]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=4, cols=3, shared_yaxes=True)

fig.add_trace(go.Bar(x=df_final['AND'].unique(), y=(df_final['AND'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              1, 1)


fig.add_trace(go.Bar(x=df_final['ARA'].unique(), y=(df_final['ARA'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              1, 2)

fig.add_trace(go.Bar(x=df_final['AST'].unique(), y=(df_final['AST'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              1, 3)

fig.add_trace(go.Bar(x=df_final['BAL'].unique(), y=(df_final['BAL'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              2, 1)


fig.add_trace(go.Bar(x=df_final['CANA'].unique(), y=(df_final['CANA'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              2, 2)


fig.add_trace(go.Bar(x=df_final['CANT'].unique(), y=(df_final['CANT'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              2, 3)

fig.add_trace(go.Bar(x=df_final['AST'].unique(), y=(df_final['AST'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              3, 1)

fig.add_trace(go.Bar(x=df_final['CAT'].unique(), y=(df_final['CAT'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              3, 2)
fig.add_trace(go.Bar(x=df_final['CLM'].unique(), y=(df_final['CLM'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              3, 3)
fig.add_trace(go.Bar(x=df_final['CYL'].unique(), y=(df_final['CYL'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              4, 1)
fig.add_trace(go.Bar(x=df_final['EUSK'].unique(), y=(df_final['EUSK'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              4, 2)
fig.add_trace(go.Bar(x=df_final['EXT'].unique(), y=(df_final['EXT'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              4, 3)



fig.update_layout(coloraxis=dict(colorscale='Bluered_r'), showlegend=False)
fig.show()

In [31]:
fig2 = make_subplots(rows=4, cols=3, shared_yaxes=True)

fig2.add_trace(go.Bar(x=df_final['GAL'].unique(), y=(df_final['GAL'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              1, 1)


fig2.add_trace(go.Bar(x=df_final['MAD'].unique(), y=(df_final['MAD'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              1, 2)

fig2.add_trace(go.Bar(x=df_final['MUR'].unique(), y=(df_final['MUR'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              1, 3)

fig2.add_trace(go.Bar(x=df_final['NAV'].unique(), y=(df_final['NAV'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              2, 1)


fig2.add_trace(go.Bar(x=df_final['RIO'].unique(), y=(df_final['RIO'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
              2, 2)


fig2.add_trace(go.Bar(x=df_final['VAL'].unique(), y=(df_final['VAL'].value_counts()),
                    marker=dict(color=[4, 5, 6], coloraxis="coloraxis")),
               2, 3)
               
fig2.update_layout(coloraxis=dict(colorscale='Bluered_r'), showlegend=False)
fig2.show()

In [32]:
df_final.AND.value_counts()

LASRPE    238
VU         17
EN         16
EX          1
Name: AND, dtype: int64

##### Habíamos cambiano los nulos por 'No Presente', pero finalmente los nulos los rellenaremos con 'NP' para seguir la nomenclatura por siglas.

In [33]:
df_final['RIO'].replace('No Presente', 'NP', inplace=True)

In [34]:
df_final

,FAMILIA,Especie_Nombre_científico,subespecie,Especie_Castellano,Ordenación_taxonómica,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
0,MEROPIDAE,Merops apiaster,NaN,Abejaruco europeo,490.0,Abejaruco europeo,Merops apiaster,NE,NaN,LC,...,NaN,NP,NaN,LC,LC,LC,2016.0,II,II,NaN
1,ACCIPITRIDAE,Pernis apivorus,NaN,Abejero europeo,174.0,Abejero europeo,Pernis apivorus,LC,NaN,NT,...,DIE,NP,NaN,LC,LC,LC,2021.0,II,II,C1
2,UPUPIDAE,Upupa epops,epops,Abubilla común,491.0,Abubilla común,Upupa epops,NE,NaN,LC,...,NaN,NP,NaN,LC,LC,LC,2020.0,II,NaN,NaN
3,PRUNELLIDAE,Prunella collaris,collaris,Acentor alpino,784.0,Acentor alpino,Prunella collaris,NE,NaN,NT,...,DIE,NP,NaN,LC,LC,LC,2016.0,II,NaN,NaN
4,PRUNELLIDAE,Prunella modularis,"modularis, mabbotti",Acentor común,785.0,Acentor común,Prunella modularis,NE,NaN,LC,...,NaN,NP,NaN,LC,LC,LC,2018.0,II,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,TURDIDAE,Turdus iliacus,"coburni, iliacus",Zorzal alirrojo,726.0,Zorzal alirrojo,Turdus iliacus,NE,DD,NaN,...,NaN,NP,NaN,NT,LC,NT,2016.0,III,NaN,NaN
380,TURDIDAE,Turdus viscivorus,viscivorus,Zorzal charlo,730.0,Zorzal charlo,Turdus viscivorus,NE,NaN,LC,...,NaN,NP,NaN,LC,LC,LC,2016.0,III,NaN,NaN
381,TURDIDAE,Turdus philomelos,"philomelos, clarkei",Zorzal común,728.0,Zorzal común,Turdus philomelos,NE,NaN,LC,...,NaN,NP,NaN,LC,LC,LC,2018.0,III,NaN,NaN
382,TURDIDAE,Turdus pilaris,NaN,Zorzal real,725.0,Zorzal real,Turdus pilaris,NE,DD,NaN,...,NaN,NP,NaN,LC,LC,LC,2016.0,III,NaN,NaN
383,NaN,NaN,NaN,NaN,NaN,Águila-azor perdicera,NaN,NaN,NaN,NaN,...,NaN,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# Eliminamos las columnas que no vamos a usar.
df_final.drop(['FAMILIA', 'Especie_Nombre_científico', 'subespecie', 'Especie_Castellano', 'Ordenación_taxonómica'], axis=1, inplace=True)
df_final

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
0,Abejaruco europeo,Merops apiaster,NE,NaN,LC,LSPE,NaN,LASRPE,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2016.0,II,II,NaN
1,Abejero europeo,Pernis apivorus,LC,NaN,NT,LSPE,I,LASRPE,NaN,NaN,...,DIE,NP,NaN,LC,LC,LC,2021.0,II,II,C1
2,Abubilla común,Upupa epops,NE,NaN,LC,LSPE,NaN,LASRPE,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2020.0,II,NaN,NaN
3,Acentor alpino,Prunella collaris,NE,NaN,NT,LSPE,NaN,LASRPE,NaN,NaN,...,DIE,NP,NaN,LC,LC,LC,2016.0,II,NaN,NaN
4,Acentor común,Prunella modularis,NE,NaN,LC,LSPE,NaN,LASRPE,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2018.0,II,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,Zorzal alirrojo,Turdus iliacus,NE,DD,NaN,NaN,II,NaN,NaN,NaN,...,NaN,NP,NaN,NT,LC,NT,2016.0,III,NaN,NaN
380,Zorzal charlo,Turdus viscivorus,NE,NaN,LC,NaN,II,NaN,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2016.0,III,NaN,NaN
381,Zorzal común,Turdus philomelos,NE,NaN,LC,NaN,II,NaN,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2018.0,III,NaN,NaN
382,Zorzal real,Turdus pilaris,NE,DD,NaN,NaN,II,NaN,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2016.0,III,NaN,NaN
383,Águila-azor perdicera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
# Hay un dato que parece vacio, los printeamos
df_final.iloc[383]

NOMBRE COMÚN                                 Águila-azor perdicera
NOMBRE CIENTÍFICO                                              NaN
LR2004 (*Canarias)                                             NaN
LISTA ROJA 2021 Invern./Migrat.                                NaN
LISTA ROJA 2021 Reproductoras (*Canarias)                      NaN
                                                     ...
GLOBAL UICN RED LIST (consulta 2022)                           NaN
GLOBAL UICN RED LIST (LAST ASSESSED)                           NaN
CON_BERN                                                       NaN
CON_BONN                                                       NaN
CON_CITES                                                      NaN
Name: 383, Length: 31, dtype: object

Efectivamente, está vacío, por lo tanto lo borramos.

In [37]:
df_final.drop(index=383, axis=0, inplace=True)
df_final

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
0,Abejaruco europeo,Merops apiaster,NE,NaN,LC,LSPE,NaN,LASRPE,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2016.0,II,II,NaN
1,Abejero europeo,Pernis apivorus,LC,NaN,NT,LSPE,I,LASRPE,NaN,NaN,...,DIE,NP,NaN,LC,LC,LC,2021.0,II,II,C1
2,Abubilla común,Upupa epops,NE,NaN,LC,LSPE,NaN,LASRPE,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2020.0,II,NaN,NaN
3,Acentor alpino,Prunella collaris,NE,NaN,NT,LSPE,NaN,LASRPE,NaN,NaN,...,DIE,NP,NaN,LC,LC,LC,2016.0,II,NaN,NaN
4,Acentor común,Prunella modularis,NE,NaN,LC,LSPE,NaN,LASRPE,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2018.0,II,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,Zarcero políglota,Hippolais polyglotta,NE,NaN,LC,LSPE,NaN,LASRPE,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2016.0,II,II,NaN
379,Zorzal alirrojo,Turdus iliacus,NE,DD,NaN,NaN,II,NaN,NaN,NaN,...,NaN,NP,NaN,NT,LC,NT,2016.0,III,NaN,NaN
380,Zorzal charlo,Turdus viscivorus,NE,NaN,LC,NaN,II,NaN,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2016.0,III,NaN,NaN
381,Zorzal común,Turdus philomelos,NE,NaN,LC,NaN,II,NaN,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2018.0,III,NaN,NaN
382,Zorzal real,Turdus pilaris,NE,DD,NaN,NaN,II,NaN,NaN,NaN,...,NaN,NP,NaN,LC,LC,LC,2016.0,III,NaN,NaN

In [38]:
# Volvemos a visualizar los nulos
df_final.isnull(). sum()

NOMBRE COMÚN                                   0
NOMBRE CIENTÍFICO                              0
LR2004 (*Canarias)                             2
LISTA ROJA 2021 Invern./Migrat.              255
LISTA ROJA 2021 Reproductoras (*Canarias)     84
                                            ...
GLOBAL UICN RED LIST (consulta 2022)          11
GLOBAL UICN RED LIST (LAST ASSESSED)          11
CON_BERN                                      33
CON_BONN                                     226
CON_CITES                                    341
Length: 31, dtype: int64

#### Por lo que se ve hay nulos excepto en 'NOMBRE COMÚN' y 'NOMBRE CIENTÍFICO' y 'RIO' porque rellenamos previamente los NaN con NP ('No Presente'). Procederemos a rellenar los nulos con 'NP' para tener una nomenclatura más uniforme.

In [39]:
df_final.fillna('NP', inplace=True)
df_final.isnull(). sum()

NOMBRE COMÚN                                 0
NOMBRE CIENTÍFICO                            0
LR2004 (*Canarias)                           0
LISTA ROJA 2021 Invern./Migrat.              0
LISTA ROJA 2021 Reproductoras (*Canarias)    0
                                            ..
GLOBAL UICN RED LIST (consulta 2022)         0
GLOBAL UICN RED LIST (LAST ASSESSED)         0
CON_BERN                                     0
CON_BONN                                     0
CON_CITES                                    0
Length: 31, dtype: int64

In [40]:
df_final

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,NAV,RIO,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,NP,NP,LC,LC,LC,2016.0,II,II,NP
1,Abejero europeo,Pernis apivorus,LC,NP,NT,LSPE,I,LASRPE,NP,NP,...,DIE,NP,NP,LC,LC,LC,2021.0,II,II,C1
2,Abubilla común,Upupa epops,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,NP,NP,LC,LC,LC,2020.0,II,NP,NP
3,Acentor alpino,Prunella collaris,NE,NP,NT,LSPE,NP,LASRPE,NP,NP,...,DIE,NP,NP,LC,LC,LC,2016.0,II,NP,NP
4,Acentor común,Prunella modularis,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,NP,NP,LC,LC,LC,2018.0,II,NP,NP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,NP,NP,LC,LC,LC,2016.0,II,II,NP
379,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NP,NP,NT,LC,NT,2016.0,III,NP,NP
380,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,NP,NP,NP,LC,LC,LC,2016.0,III,NP,NP
381,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,NP,NP,NP,LC,LC,LC,2018.0,III,NP,NP
382,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NP,NP,LC,LC,LC,2016.0,III,NP,NP

## Probamos una primera app en Dash

In [41]:
!pip install dash

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dash in /home/perseis/.local/lib/python3.10/site-packages (2.8.1)
Requirement already satisfied: Flask>=1.0.4 in /home/perseis/.local/lib/python3.10/site-packages (from dash) (2.2.3)
Requirement already satisfied: plotly>=5.0.0 in /home/perseis/.local/lib/python3.10/site-packages (from dash) (5.13.1)
Requirement already satisfied: dash-table==5.0.0 in /home/perseis/.local/lib/python3.10/site-packages (from dash) (5.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in /home/perseis/.local/lib/python3.10/site-packages (from dash) (2.0.0)
Requirement already satisfied: dash-html-components==2.0.0 in /home/perseis/.local/lib/python3.10/site-packages (from dash) (2.0.0)
Requirement already satisfied: click>=8.0 in /home/perseis/.local/lib/python3.10/site-packages (from Flask>=1.0.4->dash) (8.1.3)
Requirement already satisfied: Jinja2>=3.0 in /home/perseis/.local/lib/python3.10/site-packages (from Flask>=1.0.4->dash) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /home/perseis/.local/lib/python3.10/site-packages (from Flask>=1.0.4->dash) (2.1.2)
Requirement already satisfied: Werkzeug>=2.2.2 in /home/perseis/.local/lib/python3.10/site-packages (from Flask>=1.0.4->dash) (2.2.3)
Requirement already satisfied: tenacity>=6.2.0 in /home/perseis/.local/lib/python3.10/site-packages (from plotly>=5.0.0->dash) (8.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/perseis/.local/lib/python3.10/site-packages (from Jinja2>=3.0->Flask>=1.0.4->dash) (2.1.2)

In [42]:
from dash import Dash, dcc, html, Input, Output
import plotly.express as px
import plotly.graph_objects as go
import geopandas as gpd

In [43]:
f = r"ESP_adm/ESP_adm1.shp"
shapes = gpd.read_file(f)

In [44]:
app = Dash(__name__) # inicializamos Dash

In [45]:
#App Layout
app.layout = html.Div([ # Definimos el diseño de La Pagina HTML donde correrá nuestro programa.
    html.H1("Web Pajaritos Dash", style={'text-align' : 'center'}), # Crea La Cabecera de la pagina HTML
    dcc.Dropdown (id="slct_nombre_comun", # Crea el Desplegable
        options=[# Lista de opciones para el Desplegable (Label: Valor que aparece para el usuario || Value: Valor inte
            {"label": "Abejaruco europeo", "value": "Abejaruco europeo"}, #Como que el valor Value es un año,
            {"label":"Acentor común", "value": "Acentor común"}, # podemos dejar el valor interno
            {"label": "Chotacabras cuellirrojo", "value": "Chotacabras cuellirrojo"}, # como un INTEGER
            {"label": "Ruiseñor común", "value": "Ruiseñor común"}],
        multi=False, # Multi: Deja el Usuario introducir multiples valores a la vez
        value=2015, # Cambiamos Value a 2015 como default, asi el usuario ya tiene un mapa al entrar a la pagina
        clearable=False, # No aparece el boton de Borrar
        searchable=False, # No se puede buscar escribiendo
        style={"width": "40%"} # Style: Cambia el estilo en general del Desplegable (width: Ancho)
        ),
    html.Div(id="output_container", children= []), #Crea un bloque de texto debajo del Desplegable y crea una variable hija de t
    html. Br(), # Espacio en blanco Best InBI
    dcc.Graph(id='superstore_map', figure={}) # Crea el Mapa y crea una variable hija de tipo figura
])

In [46]:
# Conecta Los Graficos de Plotly con Los Componentes Dash
@app.callback( # Define Los Inputs y Outputs de la funcion update_graph (Actualizar Grafico)
    [Output (component_id='output_container', component_property='children'), # Output 1: Texto debajo del desplegable
    Output (component_id='superstore_map', component_property='figure')], #Output 2: Mapa
    [Input (component_id='slct_nombre_comun', component_property='value')] # Input: Año del Desplegable
    )

def update_graph (option_slctd):
    print(option_slctd) # Imprimimos a consola La opcion del usuario,
    print(type (option_slctd)) # y el tipo de la opcion (best practices).
    
    container="El año seleccionado es: {}".format(option_slctd) # Cambiamos el texto debajo del desplegable al Año introducido
    
    dff = df_final.copy() # Creamos una copia de nuestra DataFrame, asi no modificamos datos de la original
    dff = dff[dff["NOMBRE COMÚN"] == option_slctd] # Filtramos La nueva DataFrame por año, asi tenemos solo del año introducido por el us
    #Plotly Express
    #Creamos el Mapa
    fig= px.choropleth_mapbox(shapes, geojson=shapes.geometry,
        #data_frame=dff, # Definimos La DataFrame con nuestra copia
        #locationmode='ESP', # Cambiamos el Tipo de Localizacion a Estados de EEUU
        locations=shapes.index, # Cambiamos Las Localizaciones para que  nuestra columna de Codigos de Es Best InBl
        # TIENEN QUE SER LOS CODIGOS DE ESTADO, NO PUEDEN SER LOS NOMBRES!!
        #scope="europe", # estados unidos
        color='ID_1', # Definimos esta variable para cambiar La Columna que usa como referencia para añadir INTELIGESCOSOLUTIONS
        hover_name='NAME_1',
        mapbox_style="carto-positron",
        zoom=4.3, 
        center = {"lat": 39.6, "lon": -4},
        opacity=0.5, # Definimos Los valores que aparezerán al pasar el ratón sobre un estado (C
        # Como que el Color va a estar basado en % de Beneficio, Plotly automaticamente lo asigna al ultimo valor en hover_data[
        #color_continuous_scale=px.colors.sequential.YlOrRd, # Define como cambia el color con % de Beneficio
        #emplate='plotly_dark' # Plantilla (plotly. io. templates)
    )
    return container, fig # Retornar Los Objetos que hemos creado
# IMPORTANTE: Retornar Los valores en el mismo orden que pusiste en Los Outputs!

In [47]:
'''if __name__ == "__main__":
    app.run_server(debug=True, use_reloader=False)
    ''' # Corre el Servidor:
# En La Consola saldrá: "Dash is running on ", un URL donde correrá el Servidor y un WARNING en texto rojo

# Este URL seguramente será: "http://127.0.0.1:8050", que es un servidor virtual y privado en cada computadora,


#usada para desarollar y hacer pruebas del programa.
#Recuerda que ESTE URL ES PRIVADO Y VIRTUAL! No Lo uses para hacer un proyecto publico,
# tu dispositivo será el unico que, Lo podrá ver.

'if __name__ == "__main__":\n    app.run_server(debug=True, use_reloader=False)\n    '

## Continuamos con la limpieza de datos

#### Vamos a crear dos nuevas columnas:Prsencia (comunidades en la que el ave está presente), y Amenaza (las amenazas en las que se encuentra esa ave). La intención de esto es crear una entrada de cada ave por cada vez que aparezca en una comunidad, junto a su amenaza. Es decir (por ejemplo y sin saber en un principio), si el Abejaruco europeo está presente en Andalucía, Aragón y Islas Canarias, obtendremos 3 filas de Abejaruco europeo, una con la ubicación en Andalucía, otra con la ubicación en Aragón y otra con la ubicació en Canarias, con sus respectivas Amenazas.

#### Empecemos por crear estas columnas.

In [48]:
# Creamos las 2 nuevas columnas
df_final['Presente']=np.nan
df_final['Amenaza']=np.nan
# Recorremos las filas, añadiendo el nombre de las comunidades en la que el ave está presente a la columna 'Presente'
for index, row in df_final.iterrows():
    x=''
    y=''
    if row['AND'] != 'NP':
        x = x + ',' + 'Andalucía'
        z = df_final['AND'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['ARA'] != 'NP':
        x = x + ',' + 'Aragón'
        z = df_final['ARA'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['AST'] != 'NP':
        x = x + ',' + 'Principado de Asturias'
        z = df_final['AST'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['BAL'] != 'NP':
        x = x + ',' + 'Islas Baleares'
        z = df_final['BAL'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['CANA'] != 'NP':
        x = x + ',' + 'Islas Canarias'
        z = df_final['CANA'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['CANT'] != 'NP':
        x = x + ',' + 'Cantabria'
        z = df_final['CANT'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['CAT'] != 'NP':
        x = x + ',' + 'Cataluña'
        z = df_final['CAT'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['CLM'] != 'NP':
        x = x + ',' + 'Castilla-La Mancha'
        z = df_final['CLM'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['CYL'] != 'NP':
        x = x + ',' + 'Castilla y León'
        z = df_final['CYL'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['EUSK'] != 'NP':
        x = x + ',' + 'País Vasco'
        z = df_final['EUSK'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['EXT'] != 'NP':
        x = x + ',' + 'Extremadura'
        z = df_final['EXT'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['GAL'] != 'NP':
        x = x + ',' + 'Galicia'
        z = df_final['GAL'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['MAD']  != 'NP':
        x = x + ',' + 'Comunidad de Madrid'
        z = df_final['MAD'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['MUR'] != 'NP':
        x = x + ',' + 'Región de Murcia'
        z = df_final['MUR'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['NAV'] != 'NP':
        x = x + ',' + 'Comunidad Foral de Navarra'
        z = df_final['NAV'][index]
        y = y + ',' + z
        print(y)
        z = ''
    else:
        pass
    if row['RIO'] != 'NP':
        x = x + ',' + 'La Rioja'
        z = df_final['RIO'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    if row['VAL'] != 'NP':
        x = x + ',' + 'Comunidad Valenciana'
        z = df_final['VAL'][index]
        y = y + ',' + z
        z = ''
    else:
        pass
    #print(z)
    #print(index)
    df_final['Presente'][index] = x
    df_final['Amenaza'][index] = y
    

df_final

,LASRPE,DIE,REPFSA,DIE,R,SAH,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE,DIE
,LASRPE,REPFSA,R,DIE
,LASRPE,DIE,REPFSA,DIE,R,DIE,DIE,DIE
,VU,EN,EN,EX,EN,EN,EN,SAH,VU,EN,EN,EN
,LASRPE,VU,DIE,VU,REPFSA,VU,VU,VU,EN,SAH,DIE,VU
,VU,VU,VU,VU,VU,VU,VU,SAH,VU,VU,VU,EN
,LASRPE,DIE,REPFSA,VU,R,SAH,SAH,EX,VU
,LASRPE,LAESRPE,DIE,VU,EN,VU,DIE,SAH,VU,DIE,VU
,LASRPE,DIE,VU,REPFSA,DIE,EN,VU,EN,DIE,DIE
,LASRPE,REPFSA,DIE,DIE,VU
,DIE,DIE,EN,DIE,VU,DIE,DIE,VU
,LASRPE,DIE,REPFSA,VU,R,SAH,DIE,DIE
,EN,VU,DIE,VU,EN,VU,VU,VU,VU,VU,VU,EN,EX,VU
,LAESRPE,DIE,DIE,LNESRPE
,VU,EN,EN,VU,DIE,VU,SAH
,LASRPE,REPFSA,DIE,DIE,DIE
,DIE,LNESRPE
,LASRPE,DIE,REPFSA,DIE,R,DIE,DIE,VU
,LASRPE,DEP,REPFSA,DIE,DIE,SAH
,LASRPE,DIE,DIE,REPFSA,VU,R,SAH,VU,SAH,DIE,SAH
,EN,EN,EN,EN,EN,EN,EN,EN,EN
,LASRPE,DIE,DIE,REPFSA,VU,VU,SAH,DIE,DIE,VU
,EN,EN,EX,VU,SAH,SAH,EN,EN
,LASRPE,DIE,REPFSA,VU,R,DIE,DIE
,LASRPE,REPFSA,VU,R,DIE,VU,VU,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE,EX,DIE
,LASRPE,DIE,EN,DIE,EN,DIE,SAH,DIE
,LASRPE,DIE,REPFSA,VU,VU,VU,DIE,DIE
,LASRPE,VU,DIE,VU,VU,SAH,EN,EN,VU
,LASRPE,DIE,DIE,REPFSA,DIE,VU,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE
,LASRPE,VU,DIE,DIE,REPFSA,DIE,DIE,DIE,DIE,DIE,DIE
,LASRPE,LAESRPE,DIE,REPFSA,DIE,R,DIE,VU,EX,DIE
,LASRPE,DIE,DIE,REPFSA,DIE,DIE,DIE,VU,DIE,SAH
,VU,VU,DIE,VU,DIE,VU,DIE,VU,DIE,DIE
,LASRPE,EN,DIE,DIE,DIE,DIE
,LASRPE,VU,DIE,DIE,DIE
,DIE
,LASRPE,DIE,REPFSA,VU,R,DIE,DIE,DIE,DIE
,LASRPE,DIE,DIE,REPFSA,DIE,DIE,DIE
,EN,EN(Reprod.),DIE/VU,EN,DIE,R,DIE,EN,DIE,DIE
,VU,VU,VU,VU,SAH,SAH,EX,EN
,VU,VU,VU,EN,VU,SAH,SAH,VU,SAH
,LASRPE,DIE,DIE,REPFSA,DIE,DIE,DIE,SAH
,LASRPE,DIE,DIE,REPFSA,DIE,DIE,DIE
,LASRPE,LAESRPE,DIE,VU,VU,R,SAH,SAH,VU,SAH
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE
,LASRPE,DIE,DIE,REPFSA,VU,DIE,DIE,DIE
,LASRPE,DIE,REPFSA,DIE
,DIE,LNESRPE
,LASRPE,DIE,DIE,EN,REPFSA,VU,R,SAH,VU,DIE,VU
,VU,VU,EN
,LASRPE,DIE,REPFSA,VU,DIE,DIE,DIE,DIE
,LASRPE,DIE,REPFSA,VU,R,SAH,SAH,DIE,EN
,EN,EN,EN,EN,EN,EN,VU,EN,EN,EN,VU,VU
,LASRPE,EN/REPFSA,VU,DIE,VU,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE
,VU,VU,SAH
,LASRPE,DIE,REPFSA,DIE,R,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,R,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE
,VU,DIE,DIE,LNESRPE
,EN (Sist. Ib.)/LAESRPE,VU,VU,EN
,LASRPE,REPFSA,R,DIE,VU
,EN,EN
,LASRPE,SAH,REPFSA,VU,VU
,LASRPE,REPFSA,VU,DIE,VU,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE
,LASRPE,DIE,REPFSA,VU,DIE,DIE
,LASRPE,DIE,VU,VU,DIE,DIE,DIE
,REPFSA,DIE,DIE
,EN,EN,EX,EN,EN,EX,EN
,DEP,REPFSA,DIE,R,DIE,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE
,VU,EN,EN,VU,VU,EN,EN,SAH,VU,EN
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,SAH
,LASRPE,DIE,VU,DIE,DIE,DIE,DIE,DIE
,LASRPE,DIE,REPFSA,DIE,SAH
,LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE,DIE
,LASRPE,REPFSA,DIE,DIE,DIE
,EN,EN,EN,EN,EN,EN
,LASRPE,DIE,REPFSA,DIE,R,DIE,VU
,LASRPE,DIE,REPFSA,VU,DIE,SAH,DIE,SAH
,LASRPE,REPFSA,DIE,LNESRPE

/tmp/ipykernel_4284/1173804099.py:130: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_4284/1173804099.py:131: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Presente,Amenaza
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,",Andalucía,Islas Baleares,Cataluña,Castilla-La...",",LASRPE,VU,REPFSA,DIE,DIE,DIE"
1,Abejero europeo,Pernis apivorus,LC,NP,NT,LSPE,I,LASRPE,NP,NP,...,NP,LC,LC,LC,2021.0,II,II,C1,",Andalucía,Islas Baleares,Cataluña,Castilla-La...",",LASRPE,DIE,REPFSA,DIE,R,SAH,DIE,DIE"
2,Abubilla común,Upupa epops,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2020.0,II,NP,NP,",Andalucía,Islas Baleares,Islas Canarias,Catal...",",LASRPE,DIE,DIE,REPFSA,DIE,VU,DIE"
3,Acentor alpino,Prunella collaris,NE,NP,NT,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,NP,NP,",Andalucía,Islas Baleares,Cataluña,Castilla-La...",",LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE,DIE"
4,Acentor común,Prunella modularis,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2018.0,II,NP,NP,",Andalucía,Islas Baleares,Cataluña,Castilla-La...",",LASRPE,DIE,REPFSA,DIE,DIE"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,",Andalucía,Islas Baleares,Cataluña,Castilla-La...",",LASRPE,DIE,REPFSA,DIE,DIE"
379,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NT,LC,NT,2016.0,III,NP,NP,,
380,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,
381,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2018.0,III,NP,NP,,
382,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,

#### Lo tenemos, es interesante ver que las últimas aves tienen la columna 'Presente' vacía, lo que nos indica probablemente que no hay datos de esas aves.

In [49]:
df_final['CYL'].unique()

array(['NP'], dtype=object)

#### Además por lo visto ningún pájaro está presente en Castilla y León

In [50]:
# Visualizamos un dato aleatorio para ver como ha quedado.
df_final.iloc[178]['Presente']

',Andalucía,Islas Baleares,Cataluña,Castilla-La Mancha,Extremadura'

In [51]:
# Eliminamos las comas al principio de ambas columnas 'Presente' y 'Amenaza'
df_final["Presente"].replace({'^\,':''}, regex=True, inplace=True)
df_final

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Presente,Amenaza
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",",LASRPE,VU,REPFSA,DIE,DIE,DIE"
1,Abejero europeo,Pernis apivorus,LC,NP,NT,LSPE,I,LASRPE,NP,NP,...,NP,LC,LC,LC,2021.0,II,II,C1,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",",LASRPE,DIE,REPFSA,DIE,R,SAH,DIE,DIE"
2,Abubilla común,Upupa epops,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2020.0,II,NP,NP,"Andalucía,Islas Baleares,Islas Canarias,Catalu...",",LASRPE,DIE,DIE,REPFSA,DIE,VU,DIE"
3,Acentor alpino,Prunella collaris,NE,NP,NT,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,NP,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",",LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE,DIE"
4,Acentor común,Prunella modularis,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2018.0,II,NP,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",",LASRPE,DIE,REPFSA,DIE,DIE"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",",LASRPE,DIE,REPFSA,DIE,DIE"
379,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NT,LC,NT,2016.0,III,NP,NP,,
380,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,
381,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2018.0,III,NP,NP,,
382,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,

In [52]:
df_final["Amenaza"].replace({'^\,':''}, regex=True, inplace=True)
df_final

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Presente,Amenaza
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...","LASRPE,VU,REPFSA,DIE,DIE,DIE"
1,Abejero europeo,Pernis apivorus,LC,NP,NT,LSPE,I,LASRPE,NP,NP,...,NP,LC,LC,LC,2021.0,II,II,C1,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...","LASRPE,DIE,REPFSA,DIE,R,SAH,DIE,DIE"
2,Abubilla común,Upupa epops,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2020.0,II,NP,NP,"Andalucía,Islas Baleares,Islas Canarias,Catalu...","LASRPE,DIE,DIE,REPFSA,DIE,VU,DIE"
3,Acentor alpino,Prunella collaris,NE,NP,NT,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,NP,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...","LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE,DIE"
4,Acentor común,Prunella modularis,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2018.0,II,NP,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...","LASRPE,DIE,REPFSA,DIE,DIE"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...","LASRPE,DIE,REPFSA,DIE,DIE"
379,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NT,LC,NT,2016.0,III,NP,NP,,
380,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,
381,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2018.0,III,NP,NP,,
382,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,

In [53]:
# Volvemos a visualizar un dato aleatorio para ver el resultado.
df_final.iloc[334]

NOMBRE COMÚN                                                                 Roquero solitario
NOMBRE CIENTÍFICO                                                         Monticola solitarius
LR2004 (*Canarias)                                                                          NE
LISTA ROJA 2021 Invern./Migrat.                                                             NP
LISTA ROJA 2021 Reproductoras (*Canarias)                                                   LC
                                                                   ...
CON_BERN                                                                                    II
CON_BONN                                                                                    NP
CON_CITES                                                                                   NP
Presente                                     Andalucía,Islas Baleares,Cataluña,Castilla-La ...
Amenaza                                                      LASRPE,DIE,REPFSA,DIE,DIE,DIE,DIE
Name: 334, Length: 33, dtype: object

#### Ya tenemos las nuevas columnas limpias, ahora las vamos a separar y vamos a obtener varias filas de cada ave, una por comunidad en la que está presente.

In [54]:
# Creamos un dataframe solo con las columnas NOMBRE COMUN y Presente.
ubi = df_final[['NOMBRE COMÚN', 'Presente']]
ubi

          NOMBRE COMÚN                                           Presente
0    Abejaruco europeo  Andalucía,Islas Baleares,Cataluña,Castilla-La ...
1      Abejero europeo  Andalucía,Islas Baleares,Cataluña,Castilla-La ...
2       Abubilla común  Andalucía,Islas Baleares,Islas Canarias,Catalu...
3       Acentor alpino  Andalucía,Islas Baleares,Cataluña,Castilla-La ...
4        Acentor común  Andalucía,Islas Baleares,Cataluña,Castilla-La ...
..                 ...                                                ...
378  Zarcero políglota  Andalucía,Islas Baleares,Cataluña,Castilla-La ...
379    Zorzal alirrojo
380      Zorzal charlo
381       Zorzal común
382        Zorzal real

[383 rows x 2 columns]

In [55]:
# Separamos los valores por coma ',' y obtenemos un valor por fila.
#s = ubi["Presente"].str.split(",").apply(pd.Series, 1).stack().reset_index(drop=True)
s = ubi.assign(Presente=ubi['Presente'].str.split(',')).explode('Presente').reset_index(drop = True)
s

           NOMBRE COMÚN            Presente
0     Abejaruco europeo           Andalucía
1     Abejaruco europeo      Islas Baleares
2     Abejaruco europeo            Cataluña
3     Abejaruco europeo  Castilla-La Mancha
4     Abejaruco europeo          País Vasco
...                 ...                 ...
1703  Zarcero políglota         Extremadura
1704    Zorzal alirrojo
1705      Zorzal charlo
1706       Zorzal común
1707        Zorzal real

[1708 rows x 2 columns]

In [56]:
# Nombramos a esta nueva columna 'Ubicacion'
s.rename(columns={'Presente' : 'Ubicacion'}, inplace=True)
s

           NOMBRE COMÚN           Ubicacion
0     Abejaruco europeo           Andalucía
1     Abejaruco europeo      Islas Baleares
2     Abejaruco europeo            Cataluña
3     Abejaruco europeo  Castilla-La Mancha
4     Abejaruco europeo          País Vasco
...                 ...                 ...
1703  Zarcero políglota         Extremadura
1704    Zorzal alirrojo
1705      Zorzal charlo
1706       Zorzal común
1707        Zorzal real

[1708 rows x 2 columns]

In [57]:
s.drop(['NOMBRE COMÚN'], axis=1, inplace=True)
s

               Ubicacion
0              Andalucía
1         Islas Baleares
2               Cataluña
3     Castilla-La Mancha
4             País Vasco
...                  ...
1703         Extremadura
1704
1705
1706
1707

[1708 rows x 1 columns]

In [58]:
# DEl dataframe general obtenemos una fila por amenaza, separando también por la coma ','
ame = df_final.assign(Amenaza=df_final['Amenaza'].str.split(',')).explode('Amenaza').reset_index(drop = True)
ame

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Presente,Amenaza
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",LASRPE
1,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",VU
2,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",REPFSA
3,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",DIE
4,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",DIE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",DIE
1704,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NT,LC,NT,2016.0,III,NP,NP,,
1705,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,
1706,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2018.0,III,NP,NP,,
1707,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,

In [59]:
# Unimos todo en un solo dataframe.
df_definitivo = ame.join(s)
df_definitivo

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Presente,Amenaza,Ubicacion
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",LASRPE,Andalucía
1,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",VU,Islas Baleares
2,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",REPFSA,Cataluña
3,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",DIE,Castilla-La Mancha
4,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",DIE,País Vasco
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2016.0,II,II,NP,"Andalucía,Islas Baleares,Cataluña,Castilla-La ...",DIE,Extremadura
1704,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NT,LC,NT,2016.0,III,NP,NP,,,
1705,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,LC,LC,LC,2016.0,III,NP,NP,,,
1706,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,LC,LC,LC,2018.0,III,NP,NP,,,
1707,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,LC,LC,LC,2016.0,III,NP,NP,,,

In [60]:
# Eliminamos la columna 'Prsente' que ya no necesitamos.
df_definitivo.drop(['Presente'], axis=1, inplace=True)
df_definitivo

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Amenaza,Ubicacion
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,LASRPE,Andalucía
1,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,VU,Islas Baleares
2,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,REPFSA,Cataluña
3,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,Castilla-La Mancha
4,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,País Vasco
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,Extremadura
1704,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NT,LC,NT,2016.0,III,NP,NP,,
1705,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,
1706,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2018.0,III,NP,NP,,
1707,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,

In [61]:
# Rellenamos los datos vacíos de Ubicación por NP
for index, row in df_definitivo.iterrows():
    if row['Ubicacion'] == '':
        df_definitivo['Ubicacion'][index] = 'NP'
    else:
        pass

df_definitivo

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Amenaza,Ubicacion
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,LASRPE,Andalucía
1,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,VU,Islas Baleares
2,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,REPFSA,Cataluña
3,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,Castilla-La Mancha
4,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,País Vasco
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,Extremadura
1704,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NT,LC,NT,2016.0,III,NP,NP,,NP
1705,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,NP
1706,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2018.0,III,NP,NP,,NP
1707,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,NP

In [62]:
# Rellenamos los nulos en 'Ubicacion' con NP.
df_definitivo['Ubicacion'].fillna('NP', inplace=True)
df_definitivo

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,VAL,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Amenaza,Ubicacion
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,LASRPE,Andalucía
1,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,VU,Islas Baleares
2,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,REPFSA,Cataluña
3,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,Castilla-La Mancha
4,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,País Vasco
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,Zarcero políglota,Hippolais polyglotta,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,NP,LC,LC,LC,2016.0,II,II,NP,DIE,Extremadura
1704,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NP,NT,LC,NT,2016.0,III,NP,NP,,NP
1705,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,NP
1706,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2018.0,III,NP,NP,,NP
1707,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,NP,LC,LC,LC,2016.0,III,NP,NP,,NP

In [63]:
# Comprobamos que no se nos ha colado nada raro en 'Ubicacion'
df_definitivo['Ubicacion'].unique()

array(['Andalucía', 'Islas Baleares', 'Cataluña', 'Castilla-La Mancha',
       'País Vasco', 'Extremadura', 'Comunidad de Madrid',
       'Comunidad Foral de Navarra', 'Islas Canarias', 'Galicia',
       'Región de Murcia', 'Aragón', 'Cantabria', 'Comunidad Valenciana',
       'La Rioja', 'Principado de Asturias', 'NP'], dtype=object)

In [64]:
# Hacemos un conteo de cuántas son las aves de las que no hay datos por comunidad.
df_definitivo[df_definitivo['Ubicacion']=='NP'].value_counts().sum()

44

Hay 44 aves que no están presentes en ninguna región de España.

## Geopandas y las geometrías de las comunidades

#### Ya tenemos las aves separadas por ubicación con su amenaza. AHora el siguiente paso será unir cada ubicación con su geometría, para eso descargamos las geometrías del mapa de España y sus comunidades desde: http://www.diva-gis.org/gdata seleccionado España y 'Mapa por comunidad'. Nos descargará un archivo zip con una carpeta que contiene varios archivos. Esa carpeta (ESP_adm) la colocamos en el directorio raíz de este proyecto. Hay geometrías por ciudades, distrito, comunidades y otras. Nos quedaremos con la de comunidades, que son los archivos llamados ESP_adm1.
#### A partir de aquí vamos a necesitar la librería geopandas

#### PREGUNTAR A MIGUEL: qué hacemos con los pajaritos de los que no hay datos

In [65]:
# Importamos la librería geopandas, y cargamos las geometrías de las comunidades de España (ESP_adm1)
import geopandas as gpd

f = r"ESP_adm/ESP_adm1.shp"
shapes = gpd.read_file(f)
shapes

,ID_0,ISO,NAME_0,ID_1,NAME_1,TYPE_1,ENGTYPE_1,NL_NAME_1,VARNAME_1,geometry
0,215,ESP,Spain,1,Andalucía,Comunidad Autónoma,Autonomous Community,NaN,Andalousie|Andaluc¡a|Andalusien|Andaluzia,"MULTIPOLYGON (((-3.03014 35.94264, -3.03014 35..."
1,215,ESP,Spain,2,Aragón,Comunidad Autónoma,Autonomous Community,NaN,Aragão|Aragó|Aragón|Aragona|Aragonien,"POLYGON ((-0.74582 42.92190, -0.74409 42.91921..."
2,215,ESP,Spain,3,Cantabria,Comunidad Autónoma,Autonomous Community,NaN,Cantàbria|Cantábria|Cantabrie|Kantabrien,"MULTIPOLYGON (((-3.28365 43.20003, -3.28500 43..."
3,215,ESP,Spain,4,Castilla-La Mancha,Comunidad Autónoma,Autonomous Community,NaN,Castela-La Mancha|Castela-Mancha|Castella-la M...,"MULTIPOLYGON (((-3.36418 40.63507, -3.36655 40..."
4,215,ESP,Spain,5,Castilla y León,Comunidad Autónoma,Autonomous Community,NaN,Castile and Leon|Castela e Leão|Castella i Lle...,"MULTIPOLYGON (((-2.83047 42.79212, -2.82676 42..."
5,215,ESP,Spain,6,Cataluña,Comunidad Autónoma,Autonomous Community,NaN,Catalogna|Catalogne|Catalonia|Catalunha|Catalu...,"MULTIPOLYGON (((0.72958 40.78069, 0.72958 40.7..."
6,215,ESP,Spain,7,Ceuta y Melilla,Ciudades Autónomas,Autonomous City,NaN,NaN,"MULTIPOLYGON (((-4.30069 35.17319, -4.30069 35..."
7,215,ESP,Spain,8,Comunidad de Madrid,Comunidad Autónoma,Autonomous Community,NaN,Madrid|Communauté de Madrid| Community of Madr...,"MULTIPOLYGON (((-4.25646 40.66382, -4.25743 40..."
8,215,ESP,Spain,9,Comunidad Foral de Navarra,Comunidad Autónoma,Autonomous Community,NaN,Communauté forale de Navarre|Comunidade Foral ...,"POLYGON ((-1.65526 43.31251, -1.64447 43.30674..."
9,215,ESP,Spain,10,Comunidad Valenciana,Comunidad Autónoma,Autonomous Community,NaN,Valencia|Communauté de Valence|Comunidade Vale...,"MULTIPOLYGON (((-0.45708 38.16208, -0.45708 38..."
10,215,ESP,Spain,11,Extremadura,Comunidad Autónoma,Autonomous Community,NaN,Estremadura|Estrémadure,"POLYGON ((-6.23115 40.48666, -6.22380 40.48441..."
11,215,ESP,Spain,12,Galicia,Comunidad Autónoma,Autonomous Community,NaN,Galice|Gal¡cia|Galicien|Galiza|Galizia,"MULTIPOLYGON (((-8.86292 42.14764, -8.86292 42..."
12,215,ESP,Spain,13,Islas Baleares,Comunidad Autónoma,Autonomous Community,NaN,Balearic Islands|Balearen|Balearene|Baleares|I...,"MULTIPOLYGON (((1.42597 38.77736, 1.42597 38.7..."
13,215,ESP,Spain,14,Islas Canarias,Comunidad Autónoma,Autonomous Community,NaN,Canarias|Canary Islands|Canárias|Ilhas Canária...,"MULTIPOLYGON (((-17.92792 27.84958, -17.92792 ..."
14,215,ESP,Spain,15,La Rioja,Comunidad Autónoma,Autonomous Community,NaN,Rioja,"POLYGON ((-3.00470 42.64425, -2.99506 42.64193..."
15,215,ESP,Spain,16,País Vasco,Comunidad Autónoma,Autonomous Community,NaN,Basque Country|Baskenland|Basque Autonomous Co...,"MULTIPOLYGON (((-2.49458 43.36819, -2.49458 43..."
16,215,ESP,Spain,17,Principado de Asturias,Comunidad Autónoma,Autonomous Community,NaN,Astúrias|Asturie|Asturien|Asturies|Astúries|As...,"MULTIPOLYGON (((-4.57486 43.40014, -4.57486 43..."
17,215,ESP,Spain,18,Región de Murcia,Comunidad Autónoma,Autonomous Community,NaN,Murcia|Região de Múrcia|Regió de Múrcia|Région...,"MULTIPOLYGON (((-1.54680 37.40990, -1.54681 37..."

In [66]:
# Ahora cargamos la geometría de toda España que también usaremos para algunas aves.
ff = r"ESP_adm/ESP_adm0.shp"
shape_esp = gpd.read_file(ff)
shape_esp

,ID_0,ISO,NAME_0,OBJECTID_1,ISO3,NAME_ENGLI,NAME_ISO,NAME_FAO,NAME_LOCAL,NAME_OBSOL,...,CARICOM,EU,CAN,ACP,Landlocked,AOSIS,SIDS,Islands,LDC,geometry
0,215,ESP,Spain,72,ESP,Spain,SPAIN,Spain,España,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"MULTIPOLYGON (((-17.92792 27.84958, -17.92792 ..."

In [67]:
# Renombramos las columnas para que encajen
shape_esp.rename(columns={'OBJECTID_1' : 'ID_1', 'ISO3': 'NAME_1', 'NAME_ENGLI' : 'TYPE_1', 'NAME_ISO' : 'ENGTYPE_1', 'NAME_FAO' : 'NL_NAME_1', 'NAME_LOCAL' : 'VARNAME_1'}, inplace=True)
shape_esp

,ID_0,ISO,NAME_0,ID_1,NAME_1,TYPE_1,ENGTYPE_1,NL_NAME_1,VARNAME_1,NAME_OBSOL,...,CARICOM,EU,CAN,ACP,Landlocked,AOSIS,SIDS,Islands,LDC,geometry
0,215,ESP,Spain,72,ESP,Spain,SPAIN,Spain,España,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"MULTIPOLYGON (((-17.92792 27.84958, -17.92792 ..."

In [68]:
print(shape_esp.columns.values)

['ID_0' 'ISO' 'NAME_0' 'ID_1' 'NAME_1' 'TYPE_1' 'ENGTYPE_1' 'NL_NAME_1'
 'VARNAME_1' 'NAME_OBSOL' 'NAME_VARIA' 'NAME_NONLA' 'NAME_FRENC'
 'NAME_SPANI' 'NAME_RUSSI' 'NAME_ARABI' 'NAME_CHINE' 'WASPARTOF'
 'CONTAINS' 'SOVEREIGN' 'ISO2' 'WWW' 'FIPS' 'ISON' 'VALIDFR' 'VALIDTO'
 'POP2000' 'SQKM' 'POPSQKM' 'UNREGION1' 'UNREGION2' 'DEVELOPING' 'CIS'
 'Transition' 'OECD' 'WBREGION' 'WBINCOME' 'WBDEBT' 'WBOTHER' 'CEEAC'
 'CEMAC' 'CEPLG' 'COMESA' 'EAC' 'ECOWAS' 'IGAD' 'IOC' 'MRU' 'SACU' 'UEMOA'
 'UMA' 'PALOP' 'PARTA' 'CACM' 'EurAsEC' 'Agadir' 'SAARC' 'ASEAN' 'NAFTA'
 'GCC' 'CSN' 'CARICOM' 'EU' 'CAN' 'ACP' 'Landlocked' 'AOSIS' 'SIDS'
 'Islands' 'LDC' 'geometry']

In [69]:
# Eliminamos todas las columnas que no hacen falta.
shape_esp.drop(['NAME_OBSOL', 'NAME_VARIA', 'NAME_NONLA', 'NAME_FRENC',
 'NAME_SPANI', 'NAME_RUSSI', 'NAME_ARABI', 'NAME_CHINE', 'WASPARTOF',
 'CONTAINS', 'SOVEREIGN', 'ISO2', 'WWW', 'FIPS', 'ISON', 'VALIDFR', 'VALIDTO',
 'POP2000', 'SQKM', 'POPSQKM', 'UNREGION1', 'UNREGION2', 'DEVELOPING', 'CIS',
 'Transition', 'OECD', 'WBREGION', 'WBINCOME', 'WBDEBT', 'WBOTHER', 'CEEAC',
 'CEMAC', 'CEPLG', 'COMESA', 'EAC', 'ECOWAS', 'IGAD', 'IOC', 'MRU', 'SACU', 'UEMOA',
 'UMA', 'PALOP', 'PARTA', 'CACM', 'EurAsEC', 'Agadir', 'SAARC', 'ASEAN', 'NAFTA',
 'GCC', 'CSN', 'CARICOM', 'EU', 'CAN', 'ACP', 'Landlocked', 'AOSIS', 'SIDS',
 'Islands', 'LDC' ], axis=1, inplace=True)
shape_esp

,ID_0,ISO,NAME_0,ID_1,NAME_1,TYPE_1,ENGTYPE_1,NL_NAME_1,VARNAME_1,geometry
0,215,ESP,Spain,72,ESP,Spain,SPAIN,Spain,España,"MULTIPOLYGON (((-17.92792 27.84958, -17.92792 ..."

In [70]:
# Lo juntamos todo en un único geopandas.
completo = pd.concat([shapes, shape_esp], axis=0)
completo.reset_index(inplace=True)
completo

,index,ID_0,ISO,NAME_0,ID_1,NAME_1,TYPE_1,ENGTYPE_1,NL_NAME_1,VARNAME_1,geometry
0,0,215,ESP,Spain,1,Andalucía,Comunidad Autónoma,Autonomous Community,NaN,Andalousie|Andaluc¡a|Andalusien|Andaluzia,"MULTIPOLYGON (((-3.03014 35.94264, -3.03014 35..."
1,1,215,ESP,Spain,2,Aragón,Comunidad Autónoma,Autonomous Community,NaN,Aragão|Aragó|Aragón|Aragona|Aragonien,"POLYGON ((-0.74582 42.92190, -0.74409 42.91921..."
2,2,215,ESP,Spain,3,Cantabria,Comunidad Autónoma,Autonomous Community,NaN,Cantàbria|Cantábria|Cantabrie|Kantabrien,"MULTIPOLYGON (((-3.28365 43.20003, -3.28500 43..."
3,3,215,ESP,Spain,4,Castilla-La Mancha,Comunidad Autónoma,Autonomous Community,NaN,Castela-La Mancha|Castela-Mancha|Castella-la M...,"MULTIPOLYGON (((-3.36418 40.63507, -3.36655 40..."
4,4,215,ESP,Spain,5,Castilla y León,Comunidad Autónoma,Autonomous Community,NaN,Castile and Leon|Castela e Leão|Castella i Lle...,"MULTIPOLYGON (((-2.83047 42.79212, -2.82676 42..."
5,5,215,ESP,Spain,6,Cataluña,Comunidad Autónoma,Autonomous Community,NaN,Catalogna|Catalogne|Catalonia|Catalunha|Catalu...,"MULTIPOLYGON (((0.72958 40.78069, 0.72958 40.7..."
6,6,215,ESP,Spain,7,Ceuta y Melilla,Ciudades Autónomas,Autonomous City,NaN,NaN,"MULTIPOLYGON (((-4.30069 35.17319, -4.30069 35..."
7,7,215,ESP,Spain,8,Comunidad de Madrid,Comunidad Autónoma,Autonomous Community,NaN,Madrid|Communauté de Madrid| Community of Madr...,"MULTIPOLYGON (((-4.25646 40.66382, -4.25743 40..."
8,8,215,ESP,Spain,9,Comunidad Foral de Navarra,Comunidad Autónoma,Autonomous Community,NaN,Communauté forale de Navarre|Comunidade Foral ...,"POLYGON ((-1.65526 43.31251, -1.64447 43.30674..."
9,9,215,ESP,Spain,10,Comunidad Valenciana,Comunidad Autónoma,Autonomous Community,NaN,Valencia|Communauté de Valence|Comunidade Vale...,"MULTIPOLYGON (((-0.45708 38.16208, -0.45708 38..."
10,10,215,ESP,Spain,11,Extremadura,Comunidad Autónoma,Autonomous Community,NaN,Estremadura|Estrémadure,"POLYGON ((-6.23115 40.48666, -6.22380 40.48441..."
11,11,215,ESP,Spain,12,Galicia,Comunidad Autónoma,Autonomous Community,NaN,Galice|Gal¡cia|Galicien|Galiza|Galizia,"MULTIPOLYGON (((-8.86292 42.14764, -8.86292 42..."
12,12,215,ESP,Spain,13,Islas Baleares,Comunidad Autónoma,Autonomous Community,NaN,Balearic Islands|Balearen|Balearene|Baleares|I...,"MULTIPOLYGON (((1.42597 38.77736, 1.42597 38.7..."
13,13,215,ESP,Spain,14,Islas Canarias,Comunidad Autónoma,Autonomous Community,NaN,Canarias|Canary Islands|Canárias|Ilhas Canária...,"MULTIPOLYGON (((-17.92792 27.84958, -17.92792 ..."
14,14,215,ESP,Spain,15,La Rioja,Comunidad Autónoma,Autonomous Community,NaN,Rioja,"POLYGON ((-3.00470 42.64425, -2.99506 42.64193..."
15,15,215,ESP,Spain,16,País Vasco,Comunidad Autónoma,Autonomous Community,NaN,Basque Country|Baskenland|Basque Autonomous Co...,"MULTIPOLYGON (((-2.49458 43.36819, -2.49458 43..."
16,16,215,ESP,Spain,17,Principado de Asturias,Comunidad Autónoma,Autonomous Community,NaN,Astúrias|Asturie|Asturien|Asturies|Astúries|As...,"MULTIPOLYGON (((-4.57486 43.40014, -4.57486 43..."
17,17,215,ESP,Spain,18,Región de Murcia,Comunidad Autónoma,Autonomous Community,NaN,Murcia|Região de Múrcia|Regió de Múrcia|Région...,"MULTIPOLYGON (((-1.54680 37.40990, -1.54681 37..."
18,0,215,ESP,Spain,72,ESP,Spain,SPAIN,Spain,España,"MULTIPOLYGON (((-17.92792 27.84958, -17.92792 ..."

In [71]:
# Guardamos el geopandas final
#completo.to_file('Espana_y_comunidades.shp')

In [72]:
# El archivo es un GeoDataframe con muchos datos, solo nos interesan el nombre de la comunidad y su índice, para referenciarlo en el mapa.
geo = completo[['NAME_1']]
geo

                        NAME_1
0                    Andalucía
1                       Aragón
2                    Cantabria
3           Castilla-La Mancha
4              Castilla y León
5                     Cataluña
6              Ceuta y Melilla
7          Comunidad de Madrid
8   Comunidad Foral de Navarra
9         Comunidad Valenciana
10                 Extremadura
11                     Galicia
12              Islas Baleares
13              Islas Canarias
14                    La Rioja
15                  País Vasco
16      Principado de Asturias
17            Región de Murcia
18                         ESP

In [73]:
# REnombramos la columna NAME_1 a Ubicacion para entenderlo mejor
geo.rename(columns={'NAME_1' : 'Ubicacion'}, inplace=True)
geo

/tmp/ipykernel_4284/3642452816.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                     Ubicacion
0                    Andalucía
1                       Aragón
2                    Cantabria
3           Castilla-La Mancha
4              Castilla y León
5                     Cataluña
6              Ceuta y Melilla
7          Comunidad de Madrid
8   Comunidad Foral de Navarra
9         Comunidad Valenciana
10                 Extremadura
11                     Galicia
12              Islas Baleares
13              Islas Canarias
14                    La Rioja
15                  País Vasco
16      Principado de Asturias
17            Región de Murcia
18                         ESP

In [74]:
geo['Ubicacion'].iloc[18]='NP'
geo

/tmp/ipykernel_4284/1252454933.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                     Ubicacion
0                    Andalucía
1                       Aragón
2                    Cantabria
3           Castilla-La Mancha
4              Castilla y León
5                     Cataluña
6              Ceuta y Melilla
7          Comunidad de Madrid
8   Comunidad Foral de Navarra
9         Comunidad Valenciana
10                 Extremadura
11                     Galicia
12              Islas Baleares
13              Islas Canarias
14                    La Rioja
15                  País Vasco
16      Principado de Asturias
17            Región de Murcia
18                          NP

#### Como dijimos hay aves que no están en ninguna comunidad, y al unir las geometrías con las aves podrían desaparecer las aves a las que no les corresponde ninguna geometría, perdiendo así 45 datos. Vamos a cerar un dato a asignar para esas aves que no están presentes en ninguna comunidad (NP)

In [75]:
# Añadimos una fila al GeoDataFrame de las geometrías
index_ciudad = gpd.GeoDataFrame(data={'index_ciudad' : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]})
res = pd.concat([geo, index_ciudad], axis=1)
res

                     Ubicacion  index_ciudad
0                    Andalucía             0
1                       Aragón             1
2                    Cantabria             2
3           Castilla-La Mancha             3
4              Castilla y León             4
5                     Cataluña             5
6              Ceuta y Melilla             6
7          Comunidad de Madrid             7
8   Comunidad Foral de Navarra             8
9         Comunidad Valenciana             9
10                 Extremadura            10
11                     Galicia            11
12              Islas Baleares            12
13              Islas Canarias            13
14                    La Rioja            14
15                  País Vasco            15
16      Principado de Asturias            16
17            Región de Murcia            17
18                          NP            18

#### Ahora solo nos queda unir estos datos con nuestro DataSEt de aves

In [76]:
pd.set_option("display.max_rows", 20)

In [77]:
# Usamos la función merge, indicamos que se unan a partir de la columna que tienen en común ('Ubicacion)
mapping=df_definitivo.merge(res,how='inner',left_on='Ubicacion',right_on='Ubicacion')
mapping

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,EUROPEAN IUCN RED LIST BIRDS (2015),EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Amenaza,Ubicacion,index_ciudad
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2016.0,II,II,NP,LASRPE,Andalucía,0
1,Abejero europeo,Pernis apivorus,LC,NP,NT,LSPE,I,LASRPE,NP,NP,...,LC,LC,LC,2021.0,II,II,C1,LASRPE,Andalucía,0
2,Abubilla común,Upupa epops,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2020.0,II,NP,NP,LASRPE,Andalucía,0
3,Acentor alpino,Prunella collaris,NE,NP,NT,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2016.0,II,NP,NP,LASRPE,Andalucía,0
4,Acentor común,Prunella modularis,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,LC,2018.0,II,NP,NP,LASRPE,Andalucía,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,Vencejo moro,Apus affinis,NE,NP,NT,NP,NP,NP,NP,NP,...,NP,NT,LC,2016.0,NP,NP,NP,,NP,18
1704,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,NT,LC,NT,2016.0,III,NP,NP,,NP,18
1705,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,LC,LC,LC,2016.0,III,NP,NP,,NP,18
1706,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,LC,LC,LC,2018.0,III,NP,NP,,NP,18
1707,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,LC,LC,LC,2016.0,III,NP,NP,,NP,18

#### NOTA: Es muy importante que para que la unión salga bien, tanto en el GeoDataframe de las geometrías, como en el DataFRame de aves los nombres de las ubicaciones sean eactamente iguales (tener en cuenta tildes, espacios, la forma de nombrar etc...)

#### Ya tenemos el Dataset listo para trabajarlo en el mapa.

## Unificar los niveles de amenaza

#### Ahora tenemos que unificar los tipos de amenaza que son distintos en cada ciudad en una sola escala, por ejemplo de más leve a más grave. Una posible escala puede ser 'Leve', 'Medio', 'Grave', 'Muy Grave'. Mantendremos las nomenclaturas locales, y añadiremos una nueva columna con las nomenclaturas que acabamos de decidir.

In [83]:
mapping.Amenaza.unique()

array(['LASRPE', 'EN', 'VU', 'EX', 'DIE', 'DEP', 'DIE/VU', 'REPFSA',
       'EN/REPFSA', 'R', 'SAH', 'LNESRPE', 'IEC', 'LAESRPE',
       'EN(Reprod.)', 'EN (Sist. Ib.)/LAESRPE', 'LEFP', 'TUTEL', ''],
      dtype=object)

In [84]:
   
mapping.loc[df_definitivo.Amenaza == 'DIE', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'DEP', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'LASRPE', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'LAESRPE', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'LSPE', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'IEC', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'REPFSA', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'LNESRPE', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'LEFP', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'TUTEL', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'R', 'NIVEL AMENAZA'] = 1
mapping.loc[df_definitivo.Amenaza == 'VU', 'NIVEL AMENAZA'] = 2
mapping.loc[df_definitivo.Amenaza == 'SAH', 'NIVEL AMENAZA'] = 2
mapping.loc[df_definitivo.Amenaza == 'DIE/VU', 'NIVEL AMENAZA'] = 2
mapping.loc[df_definitivo.Amenaza == 'EN', 'NIVEL AMENAZA'] = 3
mapping.loc[df_definitivo.Amenaza == 'EN(Reprod.)', 'NIVEL AMENAZA'] = 3
mapping.loc[df_definitivo.Amenaza == 'EN/REPFSA', 'NIVEL AMENAZA'] = 3
mapping.loc[df_definitivo.Amenaza == 'EN(Reprod.)', 'NIVEL AMENAZA'] = 3
mapping.loc[df_definitivo.Amenaza == 'EN (Sist. Ib.)/LAESRPE', 'NIVEL AMENAZA'] = 3
mapping.loc[df_definitivo.Amenaza == 'EX', 'NIVEL AMENAZA'] = 4
mapping.loc[df_definitivo.Amenaza == '', 'NIVEL AMENAZA'] = 0

mapping

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Amenaza,Ubicacion,index_ciudad,NIVEL AMENAZA
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2016.0,II,II,NP,LASRPE,Andalucía,0,1.0
1,Abejero europeo,Pernis apivorus,LC,NP,NT,LSPE,I,LASRPE,NP,NP,...,LC,LC,2021.0,II,II,C1,LASRPE,Andalucía,0,2.0
2,Abubilla común,Upupa epops,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2020.0,II,NP,NP,LASRPE,Andalucía,0,1.0
3,Acentor alpino,Prunella collaris,NE,NP,NT,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2016.0,II,NP,NP,LASRPE,Andalucía,0,1.0
4,Acentor común,Prunella modularis,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2018.0,II,NP,NP,LASRPE,Andalucía,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,Vencejo moro,Apus affinis,NE,NP,NT,NP,NP,NP,NP,NP,...,NT,LC,2016.0,NP,NP,NP,,NP,18,1.0
1704,Zorzal alirrojo,Turdus iliacus,NE,DD,NP,NP,II,NP,NP,NP,...,LC,NT,2016.0,III,NP,NP,,NP,18,0.0
1705,Zorzal charlo,Turdus viscivorus,NE,NP,LC,NP,II,NP,NP,NP,...,LC,LC,2016.0,III,NP,NP,,NP,18,0.0
1706,Zorzal común,Turdus philomelos,NE,NP,LC,NP,II,NP,NP,NP,...,LC,LC,2018.0,III,NP,NP,,NP,18,0.0
1707,Zorzal real,Turdus pilaris,NE,DD,NP,NP,II,NP,NP,NP,...,LC,LC,2016.0,III,NP,NP,,NP,18,0.0

In [82]:
mapping[mapping['NOMBRE COMÚN']=='Abejaruco europeo']

,NOMBRE COMÚN,NOMBRE CIENTÍFICO,LR2004 (*Canarias),LISTA ROJA 2021 Invern./Migrat.,LISTA ROJA 2021 Reproductoras (*Canarias),CEEA y LESRPE,D. Aves,AND,ARA,AST,...,EUROPEAN IUCN RED LIST BIRDS (2021),GLOBAL UICN RED LIST (consulta 2022),GLOBAL UICN RED LIST (LAST ASSESSED),CON_BERN,CON_BONN,CON_CITES,Amenaza,Ubicacion,index_ciudad,NIVEL AMENAZA
0,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2016.0,II,II,NP,LASRPE,Andalucía,0,1.0
272,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2016.0,II,II,NP,VU,Islas Baleares,12,1.0
470,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2016.0,II,II,NP,REPFSA,Cataluña,5,1.0
742,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2016.0,II,II,NP,DIE,Castilla-La Mancha,3,1.0
953,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2016.0,II,II,NP,DIE,País Vasco,15,3.0
1047,Abejaruco europeo,Merops apiaster,NE,NP,LC,LSPE,NP,LASRPE,NP,NP,...,LC,LC,2016.0,II,II,NP,DIE,Extremadura,10,1.0

In [79]:
# Hay algunos errores
mapping['NIVEL AMENAZA'][mapping['Amenaza']=='DIE'].unique()

array([1., 3., 2., 4., 0.])

In [80]:
print(mapping.iloc[952])

NOMBRE COMÚN                                    Zarcero políglota
NOMBRE CIENTÍFICO                            Hippolais polyglotta
LR2004 (*Canarias)                                             NE
LISTA ROJA 2021 Invern./Migrat.                                NP
LISTA ROJA 2021 Reproductoras (*Canarias)                      LC
                                                     ...
CON_CITES                                                      NP
Amenaza                                                       DIE
Ubicacion                                      Castilla-La Mancha
index_ciudad                                                    3
NIVEL AMENAZA                                                 2.0
Name: 952, Length: 35, dtype: object

#### Ya tenemos 5 niveles unificados (el nivel 0 es que no hay datos de esa ave en ninguna comunidad)

In [81]:
# Guardamos el dataset final
mapping.to_csv('Dataset_definitivo_con_geometrias.csv')